Papers/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('papertracker/', include('papertracker.urls')),
]

papertracker/urls.py
from django.urls import path

from . import views

app_name = 'papertracker'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:conf>/', views.conference, name='conference'),
]

papertracker/models.py
from django.db import models
from django.db.models.fields import BooleanField

# Create your models here.
class Institution(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
            return str(self.name)
    
class Area(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
            return str(self.name)

class Paper(models.Model):
    title = models.CharField(max_length=200)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    year = models.IntegerField()
    single = models.BooleanField(default=False)
    double = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-id']

    def __str__(self):
            return str(self.institution.name) + ' - ' + str(self.area.name) + ' - ' + str(self.title) + ' - ' + str(self.year) 
    
class Author(models.Model):
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    
    def __str__(self):
            return str(self.paper.id) + ' - ' + str(self.name)

class Organization(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
            return str(self.name)  
        
class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
            return str(self.name)      

class CSCat(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
            return str(self.name)    

class Conference(models.Model):
    name = models.CharField(max_length=200)
    fullname = models.CharField(max_length=500)
    organizer = models.ForeignKey(Organization, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    cscat = models.ForeignKey(CSCat, on_delete=models.CASCADE, default=1)
    year = models.IntegerField()
    single = models.BooleanField(default=False)
    double = models.BooleanField(default=False)
    unknown = models.BooleanField(default=False)
    
    def __str__(self):
            return str(self.name) + ' - ' + str(self.year)
        
class ConfPaper(models.Model):
    conf = models.ForeignKey(Conference, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['-id']

    def __str__(self):
            return str(self.conf.name) + ' - ' + str(self.conf.year) + ' - ' + str(self.title) 
        
class ConfAuthor(models.Model):
    paper = models.ForeignKey(ConfPaper, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    institution = models.CharField(max_length=200)
    
    def __str__(self):
            return str(self.paper.id) + ' - ' + str(self.paper.conf.name) + ' - ' + str(self.paper.conf.year) + ' - ' + str(self.name) + ' - ' + str(self.institution)
    
         
    

papertracker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from papertracker.models import Institution, Area, Paper, Author, Conference, Organization, Category

# Create your views here.
def get_authors(papers):
    authors = Author.objects.none()
    for paper in papers:
        authors |= Author.objects.filter(paper=paper)
    return authors

def index(request):
    papers = Paper.objects.all()
    authors = get_authors(papers)
    conferences = Conference.objects.filter(year=2020)
    single = Conference.objects.filter(year=2020, single=True).count()
    double = Conference.objects.filter(year=2020, double=True).count()
    return render(request, 'papertracker/index.html', {'papers' : papers, 'authors' : authors, 'conferences' : conferences,
                                                       'single' : single, 'double' : double})
   
   
def conference(request, conf):
    confer = Conference.objects.filter(id=conf)
    if confer.exists():
        confer = confer.first()
    else:
        return redirect('papertracker:index')
    
    confers = Conference.objects.filter(name=confer.name).exclude(year=confer.year)
    single = confers.filter(single=True).count()
    double = confers.filter(double=True).count()
    
    similars = Conference.objects.filter(category=confer.category, year=confer.year, single=confer.single, double=confer.double).exclude(id=confer.id)
    return render(request, 'papertracker/conference.html', {'confer' : confer, 'confers' : confers, 'similars' : similars,
                                                            'single' : single, 'double' : double})
   
    

papertracker/templates/papertracker/conference.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<style>
body {
    font-family: 'Montserrat';
}

@media screen and (max-height: 450px) {
  
}

@media (min-width:760px) {
  
}

  


 </style>
</head>
<body>
<div class="bg-light p-4 text-center font-weight-bold border-bottom">BlindTracker</div>
<div class="bg-light">
<br>
<div class="col-12 col-xl-9 mx-auto">



	<h2 class="mt-3 mb-2 font-weight-bold">{{confer.name}} {{confer.year}}</h2>




<div class="border mb-3 bg-white shadow-sm p-2">
<p class="m-0 p-1 font-weight-bold">
{{confer.fullname}}
</p>
<p class="m-0 p-1">
<span class="pr-3">
<i class="fas fa-network-wired"></i> {{confer.category.name}}
</span>
<br>
<span class="pr-3">
<i class="fas fa-university"></i> {{confer.organizer.name}}
</span>
<br>
{% if confer.single == True %}
<i class="fas fa-circle"></i> BLIND REVIEW
{% else %}
<i class="fas fa-circle"></i><i class="fas fa-circle"></i> DOUBLE-BLIND REVIEW
{% endif %}
</p>
</div>

<div class="mt-5 mb-3">
<h4 class="font-weight-bold">The {{confer.name}} Conference Series
<span class="float-right">
{{single}} <i class="fas fa-circle text-warning"></i> | {{double}} <i class="fas fa-circle text-warning"></i><i class="fas fa-circle text-warning"></i>
</span>

</h4>

<div class="container">
<div class="row">
{% for conf in confers %}
<div class="border mb-3 bg-white shadow-sm col-12 col-sm-6 p-2">
<h4 class="m-0 p-1 font-weight-bold">
<a href="{% url 'papertracker:conference' conf.id %}" class="text-info font-weight-bold">
{{conf.name}} {{conf.year}}
</a>
</h4>
<p class="m-0 p-1 font-weight-bold">
{{conf.fullname}}
</p>
<p class="m-0 p-1">
<span class="pr-3">
<i class="fas fa-network-wired"></i> {{conf.category.name}}
</span>
<span class="pr-3">
<i class="fas fa-university"></i> {{conf.organizer.name}}
</span>
<br>
{% if conf.single == True %}
<i class="fas fa-circle"></i> BLIND REVIEW
{% else %}
<i class="fas fa-circle"></i><i class="fas fa-circle"></i> DOUBLE-BLIND REVIEW
{% endif %}
</p>
</div>
{% endfor %}
</div>
</div>
</div>
<h4 class="font-weight-bold mt-5 mb-3">Similar Conferences</h4>
{% for conf in similars %}
<div class="border mb-3 bg-white shadow-sm p-2">
<h4 class="m-0 p-1 font-weight-bold">
<a href="{% url 'papertracker:conference' conf.id %}" class="text-info font-weight-bold">
{{conf.name}} {{conf.year}}
</a>
</h4>
<p class="m-0 p-1 font-weight-bold">
{{conf.fullname}}
</p>
<p class="m-0 p-1">
<span class="pr-3">
<i class="fas fa-network-wired"></i> {{conf.category.name}}
</span>
<span class="pr-3">
<i class="fas fa-university"></i> {{conf.organizer.name}}
</span>
{% if conf.single == True %}
<i class="fas fa-circle"></i> BLIND REVIEW
{% else %}
<i class="fas fa-circle"></i><i class="fas fa-circle"></i> DOUBLE-BLIND REVIEW
{% endif %}
</p>
</div>
{% endfor %}

</div>
</div>
</body>
</html>

papertracker/templates/papertracker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<style>
body {
    font-family: 'Montserrat';
}

@media screen and (max-height: 450px) {
  
}

@media (min-width:760px) {
  
}

  


 </style>
</head>
<body>
<div class="bg-light p-4 text-center font-weight-bold border-bottom">BlindTracker</div>
<div class="bg-light">
<br>
<br>
<div class="col-12 col-xl-9 mx-auto">
<h3 class="font-weight-bold mt-3 mb-3">All the Conferences in 2020</h3>
<p class="m-0 p-0 text-right">
{{single}} BLIND, {{double}} DOUBLE BLIND
</p>
{% for conf in conferences %}
<div class="border mb-3 bg-white shadow-sm p-2">
<h4 class="m-0 p-1">
<a href="{% url 'papertracker:conference' conf.id %}" class="text-info font-weight-bold">
{{conf.name}} {{conf.year}}
</a>
<span class="float-right text-warning"style="font-size:16px;">
{% if conf.single == True %}
	<i class="fas fa-circle"></i>
{% else %}
	<i class="fas fa-circle"></i><i class="fas fa-circle"></i>
{% endif %}
</span>
</h4>
<p class="m-0 p-1 font-weight-bold">
{{conf.fullname}}
</p>
<p class="m-0 p-1">
<span class="pr-3">
<i class="fas fa-network-wired"></i> {{conf.category.name}}
</span>
<span class="pr-3">
<i class="fas fa-university"></i> {{conf.organizer.name}}
</span>
<br>
{% if conf.single == True %}
<i class="fas fa-circle"></i> BLIND REVIEW
{% else %}
<i class="fas fa-circle"></i><i class="fas fa-circle"></i> DOUBLE-BLIND REVIEW
{% endif %}
</p>
</div>
{% endfor %}


<p>All the papers</p>
{% for paper in papers %}
<div class="border mb-3 bg-white shadow-sm">
<h4 class="m-0 p-1">{{paper.title}}</h4>
<p class="m-0 p-1">
<span class="float-right">{{paper.year}}</span>
</p>
<p class="mt-0 mb-3 p-1">
{% for author in authors %}
{% if author.paper.id == paper.id %}
<span class="border p-2">{{author.name}}</span>
{% endif %}
{% endfor %}
</p>
</div>
{% endfor %}
</div>
</div>
</body>
</html>